import type { Metadata } from 'next';
import './globals.css';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import LayoutClient from '@/layout/LayoutClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
  params: {
    lang: string;
  };
}

export default async function RootLayout({ children, params }: Props) {
  const messages = await getMessages();
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body className={'antialiased font-helvetica font-normal'}>
        <NextIntlClientProvider messages={messages}>
          <LayoutClient>{children}</LayoutClient>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
